/* This source code licensed under the GNU Affero General Public License */

using Highpoint.Sage.SimCore;
using System;

namespace Highpoint.Sage.Mathematics
{
    /// <summary>
    /// The ITimeSpanDistribution interface produces a sequence of TimeSpan values.
    /// They are generated by a class that ensures that the values that are generated
    /// conform to a particular distribution.
    /// </summary>
    public interface ITimeSpanDistribution : IModelObject
    {

        /// <summary>
        /// Gets the next value in this distribution.
        /// </summary>
        /// <returns>The next value in this distribution.</returns>
        TimeSpan GetNext();

        /// <summary>
        /// Gets the Y (distribution) value with the specified X (cumulative probability) value. For example,
        /// if the caller wishes to know what duration will, with 90% certainty, always be greater than or equal
        /// to a duration returned from the distribution, he would ask for GetValueWithCumulativeProbability(0.90);
        /// <para>Note: The median value of the distribution will be GetValueWithCumulativeProbability(0.50);</para>
        /// </summary>
        /// <param name="probability">The probability.</param>
        /// <returns></returns>
        TimeSpan GetValueWithCumulativeProbability(double probability);

        /// <summary>
        /// Sets the interval on which the CDF is queried for X. The RNG internally generates a number 'x' on (0..1), and CDF(x) is the output
        /// random number on the distribution. For the purpose of generating a schedule, running monte-carlo simulations
        /// of schedules and other related tasks, we may want to generate randoms on just a portion of that CDF, say
        /// instead of (0..1), perhaps (0..0.95), or if we want the mean value, we would use an interval of (0.5,0.5).
        /// </summary>
        /// <param name="low">The low bound (inclusive).</param>
        /// <param name="high">The high bound (exclusive, unless low and high are equal).</param>
        void SetCDFInterval(double low, double high);

    }

}